"""init

Revision ID: 3d67b3b76bfe
Revises: e3cf3e776d7b
Create Date: 2026-01-02 09:23:28.669116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d67b3b76bfe'
down_revision: Union[str, Sequence[str], None] = 'e3cf3e776d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sellers_id'), table_name='Sellers')
    op.drop_table('Sellers')
    op.add_column('Products', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('Products', sa.Column('at_create', sa.Date(), nullable=True))
    op.add_column('Products', sa.Column('seller', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'seller')
    op.drop_column('Products', 'at_create')
    op.drop_column('Products', 'source')
    op.create_table('Sellers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=False),
    sa.Column('at_create', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sellers_id'), 'Sellers', ['id'], unique=False)
    # ### end Alembic commands ###
